# =======================================================================================================
#                             o$$$$$o.   o$$$$$o   d$$$$$$o.  d$$$$$$$b
#                            d$$*`*$$$  d$$*`*$$b  $$$``*$$$  $$$^^^^^"
#                            $$$        $$$   $$$  $$$   $$$  $$$xxxx, 
#                            $$$   ,,,  $$$   $$$  $$$   $$$  $$$****` 
#                            *$$bod$$I  Y$$bod$$Y  $$$ood$$Y  $$$xxxxo,
#                             *$$$$$*    *$$$$$*   ^$$$$$$*   ^$$$$$$$^
#
# 			                 	       DO NOT EDIT THIS FILE
# =======================================================================================================
# defines code related to setting up home directory

import os
from pathlib import Path
import tempfile
import subprocess
import re
import importlib.util

import options
import utils

# checks if a copr is enabled by name
def coprIsEnabled(copr):
    coprListCmd = "dnf copr list"
    coprList = subprocess.run(coprListCmd, capture_output=True, text=True, shell=True).stdout

    coprRegexUncompiled = f"{copr}.*"
    coprRegex = re.compile(coprRegexUncompiled)
    match = re.search(coprRegex, coprList)

    if match:
        disabledRegex = r"\(disabled\)"
        return not re.search(disabledRegex, match.group(0))
    else:
        return False

# cleans a list or single package into a list of string package names
def cleanPackageInput(pkgInput):
    if utils.isString(pkgInput):
        return [ pkgInput ]
    elif utils.isList(pkgInput):
        return list(filter(utils.isString, pkgInput))
    else:
        return []

# install a list of packages passed as a list of strings using the given command
def installPackagesOrPaks(cmd, pkgList):
    # the list of well-formed packages
    goodPkgs = cleanPackageInput(pkgList)

    if goodPkgs:
        # the command used to install basePkgs
        goodPkgsCmd = f"{cmd} {" ".join(goodPkgs)}"

        # install base packages
        print(goodPkgsCmd)
        subprocess.run(goodPkgsCmd, shell=True)

# install a list of packages, passed as a list of strings
def installPackages(pkgList):
    installPackagesOrPaks("sudo dnf install", pkgList)

# install a special package
def installSpecialPackage(pkgConfig):
    # ensure that we have a valid package list
    pkgList = []
    if "pkgs" in pkgConfig:
        pkgList = pkgConfig["pkgs"]
    elif "pkg" in pkgConfig:
        pkgList = pkgConfig["pkg"]
    pkgList = cleanPackageInput(pkgList)
    if not pkgList:
        utils.eprint("ERROR: Invalid package config received (no valid package list found)")
        return

    # check that after is valid, if it exists
    after = None
    if "after" in pkgConfig:
        after = pkgConfig["after"]
        if not callable(after) and not utils.isString(after):
            utils.eprint("ERROR: Invalid package config received (value provided as after is not callable nor a string)")
            return

    # check for copr definition and enable if found
    if "copr" in pkgConfig:
        copr = pkgConfig["copr"]

        # ensure valid copr (is a string)
        if not utils.isString(copr):
            utils.eprint("ERROR: Invalid package config received (provided copr host is not a string)")
            return

        # run command to enable copr host if not already enabled
        if not coprIsEnabled(copr):
            coprCmd = f"sudo dnf copr enable {copr}"
            print(coprCmd)
            subprocess.run(coprCmd, shell=True)

    # install packages
    installPackages(pkgList)

    # run after command
    if after:
        if callable(after):
            after()
        else:
            subprocess.run(after, shell=True)

# install a list of flatpaks, passed as a list of strings
def installFlatpaks(pakList, remote="flathub"):
    installPackagesOrPaks(f"flatpak install {remote}", pakList)

# install a special package
def installSpecialFlatpaks(pakConfig):
    # ensure that we have a valid package list
    pakList = []
    if "flatpaks" in pakConfig:
        pakList = pakConfig["flatpaks"]
    elif "flatpak" in pakConfig:
        pakList = pakConfig["flatpak"]
    pakList = cleanPackageInput(pakList)
    if not pakList:
        utils.eprint("ERROR: Invalid flatpak config received (no valid flatpak list found)")
        return

    # check that after is valid, if it exists
    after = None
    if "after" in pakConfig:
        after = pakConfig["after"]
        if not callable(after) and not utils.isString(after):
            utils.eprint("ERROR: Invalid flatpak config received (value provided as after is not callable nor a string)")
            return

    # check for remote definition
    remote = "flathub"
    if "remote" in pakConfig:
        remote = pakConfig["remote"]

        # ensure valid copr (is a string)
        if not utils.isString(remote):
            utils.eprint("ERROR: Invalid flatpak config received (provided flatpak remote is not a string)")
            return

    # install packages
    installFlatpaks(pakList, remote=remote)

    # run after command
    if after:
        if callable(after):
            after()
        else:
            subprocess.run(after, shell=True)

def enableFlatpakRemotes(remotes):
    for remote in remotes:
        if not "name" in remote:
            utils.eprint("ERROR: Invalid flatpak remote received (provided remote has no name)")

        if not "url" in remote:
            utils.eprint("ERROR: Invalid flatpak remote received (provided remote has no url)")

        cmd = f"flatpak remote-add --if-not-exists {remote["name"]} {remote["url"]}"
        print(cmd)
        subprocess.run(cmd, shell=True)

# sets up rpm fusion
def setupRpmFusion():
    rpmPkgs = [
        "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm",
        "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm",
    ]
    print("Setting up RPM Fusion...")
    installPackages(rpmPkgs)
    print("RPM Fusion Installed...")

# runs the setup steps for downloading packages
def setupPackages():
    print("Installing packages...")
    # the list of "normal" packages
    basePkgs = list(filter(utils.isString, options.pkgs))

    # ensure git is installed, CRUCIAL step
    basePkgs.append("git")

    # install normal packages
    installPackages(basePkgs)

    # the list of "special" packages with extra instructions
    specialPkgs = list(filter(utils.isDict, options.pkgs))

    # install special packages
    for pkgConfig in specialPkgs:
        installSpecialPackage(pkgConfig)
    print("Package installation complete.")

# runs the steps for installing flatpaks
def setupFlatpaks():
    # ensure flatpak is installed
    print("Installing flatpak...")
    installPackages("flatpak")
    print("Flatpak Installed...")

    print("Enabling Flatpak remotes...")
    # ensure flathub is installed
    enableFlatpakRemotes([
        {
            "name": "flathub",
            "url": "https://flathub.org/repo/flathub.flatpakrepo",
        }
    ])
    enableFlatpakRemotes(options.flatpakRemotes)
    print("Flatpak remotes enabled")

    print("Installing flatpaks...")

    # the list of "normal" flatpaks
    basePaks = list(filter(utils.isString, options.flatpaks))

    # install "normal" flatpaks
    installFlatpaks(basePaks)

    # the list of "special" flatpaks with extra instructions
    specialPaks = list(filter(utils.isDict, options.flatpaks))

    # install special packages
    for pakConfig in specialPaks:
        installSpecialFlatpaks(pakConfig)
    print("Flatpaks installed.")

# the callback function used to run file after-copy functions
def fileAfterRunner(dstPath, written, afterFilesPath):
    # the path of the associated after module will be
    homeRelativePath = Path(dstPath).relative_to(Path.home())
    configAfterPath = Path(afterFilesPath) / homeRelativePath
    modulePath = Path(str(configAfterPath) + ".py")

    if modulePath.is_file():
        # import the module
        spec = importlib.util.spec_from_file_location("after", modulePath)
        afterModule = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(afterModule)

        if afterModule.always() or written:
            afterModule.callback(Path(dstPath))

def systemFileAfterRunner(dstPath, written):
    fileAfterRunner(dstPath, written, options.afterSystemFilesPath)

def homeFileAfterRunner(dstPath, written):
    fileAfterRunner(dstPath, written, options.afterUserFilesPath)

# runs the setup steps for updating system files
def setupSystemDirectories():
    print("Setting up system files...")
    utils.cpImproved(
        options.staticSystemFilesPath,
        Path.home(),
        sudo=True,
        after=systemFileAfterRunner
    )
    utils.cpImproved(
        options.templateSystemFilesPath,
        Path.home(),
        allowOverwrite=False,
        sudo=True,
        after=systemFileAfterRunner
    )
    print("System file setup complete")

# runs the setup steps for updating the home directory
def setupHomeDirectory():
    print("Setting up home files...")
    utils.cpImproved(
        options.staticUserFilesPath,
        Path.home(),
        after=homeFileAfterRunner
    )
    utils.cpImproved(
        options.templateUserFilesPath,
        Path.home(),
        allowOverwrite=False,
        after=homeFileAfterRunner
    )
    print("Home file setup complete")

# installs a single font to the machine, given as a path
def installFontByPath(path):
    fontDir = Path.home() / ".local/share/fonts"

    extension = "".join(path.suffixes)
    name = path.stem
    outputPath = os.path.join(str(fontDir), name)

    def installZip(path):
        subprocess.run(f"unzip {str(path)} -d {outputPath}", shell=True)

    installRouter = {
        ".zip": installZip
    }

    if extension in installRouter:
        installRouter[extension](path)
    else:
        utils.eprint(f"ERROR: Unable to handle font with extension '{extension}'")

# runs the setup steps for downloading and installing fonts
def installFonts():
    fontDir = str(Path.home() / ".local/share/fonts")
    subprocess.run(f"mkdir -p {fontDir}", shell=True)

    for url in options.fontUrls:
        if not utils.isString(url):
            utils.eprint("ERROR: Got invalid font data (nonString url)")
            break;
        
        with tempfile.TemporaryDirectory() as tempDir:
            subprocess.run(f"curl --output-dir {tempDir} -LO {url}", shell=True)

            files = list(Path(tempDir).glob('*'))

            if files:
                fontFile = files[0]
                installFontByPath(fontFile)
            else:
                utils.eprint(f"ERROR: Unable to zipfile download from {url}")
                break;

    subprocess.run("fc-cache -f -v", shell=True)
            
# sets up all fonts
def setupFonts():
    print("Setting up fonts...")
    installFonts()
    print("Font setup complete")

# runs the after function in options.after()
def setupAfter():
    print("Running options.after()...")
    afterFunc = getattr(options, "after", None)
    if callable(afterFunc):
        afterFunc()
    print("options.after() complete")

# runs all setup steps
def setupAll():
    setupRpmFusion()
    setupPackages()
    setupFlatpaks()
    setupFonts()
    setupSystemDirectories()
    setupHomeDirectory()
    setupAfter()

def main():
    prompt = ("Press a key to select a setup option:\n"
        "a - set up all\n"
        "h - set up home directory only\n"
        "s - set up system directories only\n"
        "f - set up fonts only\n"
        "k - set up flatpaks only\n"
        "p - set up packages only\n"
        "r - set up rpm fusion\n"
        "z - run options.after() only\n"
        "q - quit\n")

    cancelWarning = "Setup Cancelled."

    actionMap = {
        "a": setupAll,
        "s": setupSystemDirectories,
        "h": setupHomeDirectory,
        "f": setupFonts,
        "k": setupFlatpaks,
        "p": setupPackages,
        "r": setupRpmFusion,
        "z": setupAfter,
    }

    try:
        char = None
        while char != "q":
            char = input(prompt)

            if char in actionMap:
                actionMap[char]()
                print("Quick Setup Complete!")
                return
        if char == "q":
            print(cancelWarning)
    except KeyboardInterrupt:
        print(cancelWarning)

if __name__ == "__main__":
    main()
