# =======================================================================================================
#                             o$$$$$o.   o$$$$$o   d$$$$$$o.  d$$$$$$$b
#                            d$$*`*$$$  d$$*`*$$b  $$$``*$$$  $$$^^^^^"
#                            $$$        $$$   $$$  $$$   $$$  $$$xxxx, 
#                            $$$   ,,,  $$$   $$$  $$$   $$$  $$$****` 
#                            *$$bod$$I  Y$$bod$$Y  $$$ood$$Y  $$$xxxxo,
#                             *$$$$$*    *$$$$$*   ^$$$$$$*   ^$$$$$$$^
#
# 			                 	       DO NOT EDIT THIS FILE
# =======================================================================================================
# defines code related to setting up home directory

import os
from pathlib import Path
import tempfile
import subprocess

import options
import utils

# cleans a list or single package into a list of string package names
def cleanPackageInput(pkgInput):
    if utils.isString(pkgInput):
        return [ pkgInput ]
    elif utils.isList(pkgInput):
        return list(filter(utils.isString, pkgInput))
    else:
        return []

# install a list of packages, passed as a list of strings
def installPackages(pkgList):
    # the list of well-formed packages
    goodPkgs = cleanPackageInput(pkgList)

    # the command used to install basePkgs
    goodPkgsCmd = f"sudo dnf install {" ".join(goodPkgs)}"

    # install base packages
    print(goodPkgsCmd)
    subprocess.run(goodPkgsCmd, shell=True)

# install a special package
def installSpecialPackage(pkgConfig):
    # ensure that we have a valid package list
    pkgList = []
    if "pkgs" in pkgConfig:
        pkgList = pkgConfig["pkgs"]
    elif "pkg" in pkgConfig:
        pkgList = pkgConfig["pkg"]
    pkgList = cleanPackageInput(pkgList)
    if not pkgList:
        utils.eprint("ERROR: Invalid package config received (no valid package list found)")
        return

    # check that after is valid, if it exists
    after = None
    if "after" in pkgConfig:
        after = pkgConfig["after"]
        if not callable(after) and not utils.isString(after):
            utils.eprint("ERROR: Invalid package config received (value provided as after is not callable nor a string)")
            return

    # check for copr definition and enable if found
    if "copr" in pkgConfig:
        copr = pkgConfig["copr"]

        # ensure valid copr (is a string)
        if not utils.isString(copr):
            utils.eprint("ERROR: Invalid package config received (provided copr host is not a string)")
            return

        # run command to enable copr host
        coprCmd = f"sudo dnf copr enable {copr}"
        print(coprCmd)
        subprocess.run(coprCmd, shell=True)

    # install packages
    installPackages(pkgList)

    # run after command
    if after:
        if callable(after):
            after()
        else:
            subprocess.run(after, shell=True)

# runs the setup steps for downloading packages
def setupPackages():
    print("Installing packages...")
    # the list of "normal" packages
    basePkgs = list(filter(utils.isString, options.pkgs))

    # ensure git is installed, CRUCIAL step
    basePkgs.append("git")

    # install normal packages
    installPackages(basePkgs)

    # the list of "special" packages with extra instructions
    specialPkgs = list(filter(utils.isDict, options.pkgs))

    # install special packages
    for pkgConfig in specialPkgs:
        installSpecialPackage(pkgConfig)
    print("Package installation complete.")

# runs the setup steps for updating the home directory
def setupHomeDirectory():
    # copy this directory structure recursively and interactively into home, as long as this script isn't running from home directory
    if os.getcwd() == os.path.expanduser("~"):
        print("File setup skipped (running from home directory)")
    else:
        print("Setting up files...")
        utils.cpImproved(options.staticUserFilesPath, "~")
        utils.cpImproved(options.templateUserFilesPath, "~", allowOverwrite=False)
        print("File setup complete")

# installs a single font to the machine, given as a path
def installFontByPath(path):
    fontDir = "~/.local/share/fonts"

    extension = "".join(path.suffixes)
    name = path.stem
    outputPath = os.path.join(fontDir, name)

    def installZip(path):
        subprocess.run(f"unzip {str(path)} -d {outputPath}", shell=True)

    installRouter = {
        ".zip": installZip
    }

    if extension in installRouter:
        installRouter[extension](path)
    else:
        utils.eprint(f"ERROR: Unable to handle font with extension '{extension}'")

# runs the setup steps for downloading and installing fonts
def installFonts():
    fontDir = "~/.local/share/fonts"
    subprocess.run(f"mkdir -p {fontDir}", shell=True)

    for url in options.fontUrls:
        if not utils.isString(url):
            utils.eprint("ERROR: Got invalid font data (nonString url)")
            break;
        
        with tempfile.TemporaryDirectory() as tempDir:
            subprocess.run(f"curl --output-dir {tempDir} -LO {url}", shell=True)

            files = list(Path(tempDir).glob('*'))

            if files:
                fontFile = files[0]
                installFontByPath(fontFile)
            else:
                utils.eprint(f"ERROR: Unable to zipfile download from {url}")
                break;

    subprocess.run("fc-cache -f -v", shell=True)
            
# sets up all fonts
def setupFonts():
    print("Setting up fonts...")
    installFonts()
    print("Font setup complete")

# runs the after function in options.after()
def setupAfter():
    print("Running options.after()...")
    afterFunc = getattr(options, "after", None)
    if callable(afterFunc):
        afterFunc()
    print("options.after() complete")

# runs all setup steps
def setupAll():
    setupPackages()
    setupFonts()
    setupHomeDirectory()
    setupAfter()

def main():
    prompt = ("Press a key to select a setup option:\n"
        "a - set up all\n"
        "d - set up home directory only\n"
        "p - set up packages only\n"
        "f - set up fonts only\n"
        "z - run options.after() only\n"
        "q - quit\n")

    cancelWarning = "Setup Cancelled."

    actionMap = {
        "a": setupAll,
        "d": setupHomeDirectory,
        "p": setupPackages,
        "f": setupFonts,
        "z": setupAfter,
    }

    try:
        char = None
        while char != "q":
            char = input(prompt)

            if char in actionMap:
                actionMap[char]()
                print("Quick Setup Complete!")
                return
        if char == "q":
            print(cancelWarning)
    except KeyboardInterrupt:
        print(cancelWarning)

if __name__ == "__main__":
    main()
