# =======================================================================================================
#                             o$$$$$o.   o$$$$$o   d$$$$$$o.  d$$$$$$$b
#                            d$$*`*$$$  d$$*`*$$b  $$$``*$$$  $$$^^^^^"
#                            $$$        $$$   $$$  $$$   $$$  $$$xxxx, 
#                            $$$   ,,,  $$$   $$$  $$$   $$$  $$$****` 
#                            *$$bod$$I  Y$$bod$$Y  $$$ood$$Y  $$$xxxxo,
#                             *$$$$$*    *$$$$$*   ^$$$$$$*   ^$$$$$$$^
#
# 			                 	       DO NOT EDIT THIS FILE
# =======================================================================================================
# defines code related to setting up home directory

import os
import sys
from pathlib import Path
import tempfile
import subprocess
import re
import importlib.util
import configparser

import options
import utils

MODULE_CONFIG_PATH = Path(Path.home() / ".config/FedoraConfigModules.ini")

# gets an array containing the names of each module defined in this repo
def definedModules():
    folder_path = Path(__file__).parent / "modules"
    if not Path(folder_path).exists():
        return []
    return [entry.name for entry in os.scandir(folder_path) if entry.is_dir()]

# prompts the user for which modules they want to enable
# returns a list containing the names of each newly enabled module
def promptEnableModules(defined_modules):
    if len(defined_modules) <= 0:
        return []

    print("It looks like this is your first time setting up this system.")

    if not utils.askYesNo("Would you like to enable any modules before setup?"):
        print("Proceeding with setup.")
        return []

    enabled = []
    for module in defined_modules:
        if utils.askYesNo(f"Would you like to enable module '{module}'?"):
            enabled.append(module)
        
    print("Proceeding with setup.")

    return enabled

# returns the enabled modules from the passed .ini file path
# this may modify the passed file if...
#   1) there are modules enabled in the file that are not defined in this repo (removes them)
#   2) there are modules in this repo that are not explicitly disabled in the file (adds them as disabled)
def listEnabledModules(config_path):
    defined = definedModules()
    enabled = []

    default_settings = {}
    for module in defined:
        default_settings[module] = "no";

    # the initial configuration
    config = configparser.ConfigParser(defaults=default_settings, allow_unnamed_section=True)
    if Path(config_path).exists():
        config.read(config_path)
    else:
        config[configparser.UNNAMED_SECTION] = {}
        for module in promptEnableModules(defined):
            config.set(configparser.UNNAMED_SECTION, module, str(True))

    # put put config file into new config file (to remove unrecognized options)
    new_config = configparser.ConfigParser(allow_unnamed_section=True)
    new_config[configparser.UNNAMED_SECTION] = {}
    for module in defined:
        is_enabled = config.getboolean(configparser.UNNAMED_SECTION, module, fallback=False)
        new_config.set(configparser.UNNAMED_SECTION, module, str(is_enabled))
        if is_enabled:
            enabled.append(module)

    # write the new file
    subprocess.run(["touch", config_path])
    with open(str(config_path), 'w') as configfile:
        new_config.write(configfile)

    return enabled

# gets the path to all folders of enabled modules, the top level directory folder is prepended automatically
def getEnabledModulePaths(config_path):
    enabled_names = listEnabledModules(config_path)
    enabled = list(map(lambda name: Path(__file__).parent / "modules" / name, enabled_names))
    enabled.insert(0, Path(__file__).parent)
    return enabled

# imports all enabled modules, returning them in an array, which should be loaded in the given order
def importEnabledModules(config_path):
    imports = []

    module_paths = getEnabledModulePaths(config_path)
    for modulePath in module_paths:
        if not (modulePath / "options.py").is_file():
            raise FileNotFoundError(f"module '{modulePath.name}' is missing an options.py file")

        spec = importlib.util.spec_from_file_location("after", modulePath / "options.py")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        imports.append(module)

    return imports

# checks if a copr is enabled by name
def coprIsEnabled(copr):
    coprListCmd = "dnf copr list"
    coprList = subprocess.run(coprListCmd, capture_output=True, text=True, shell=True).stdout

    coprRegexUncompiled = f"{copr}.*"
    coprRegex = re.compile(coprRegexUncompiled)
    match = re.search(coprRegex, coprList)

    if match:
        disabledRegex = r"\(disabled\)"
        return not re.search(disabledRegex, match.group(0))
    else:
        return False

# cleans a list or single package into a list of string package names
def cleanPackageInput(pkgInput):
    if utils.isString(pkgInput):
        return [ pkgInput ]
    elif utils.isList(pkgInput):
        return list(filter(utils.isString, pkgInput))
    else:
        return []

# install a list of packages passed as a list of strings using the given command
def installPackagesOrPaks(cmd, pkgList):
    # the list of well-formed packages
    goodPkgs = cleanPackageInput(pkgList)

    if goodPkgs:
        # the command used to install basePkgs
        goodPkgsCmd = f"{cmd} {" ".join(goodPkgs)}"

        # install base packages
        print(goodPkgsCmd)
        subprocess.run(goodPkgsCmd, shell=True)

# install a list of packages, passed as a list of strings
def installPackages(pkgList):
    installPackagesOrPaks("sudo dnf install", pkgList)

# install a special package
def installSpecialPackage(pkgConfig):
    # ensure that we have a valid package list
    pkgList = []
    if "pkgs" in pkgConfig:
        pkgList = pkgConfig["pkgs"]
    elif "pkg" in pkgConfig:
        pkgList = pkgConfig["pkg"]
    pkgList = cleanPackageInput(pkgList)
    if not pkgList:
        utils.eprint("ERROR: Invalid package config received (no valid package list found)")
        return

    # check that before is valid, if it exists
    before = None
    if "before" in pkgConfig:
        before = pkgConfig["before"]
        if not callable(before) and not utils.isString(before):
            utils.eprint("ERROR: Invalid package config received (value provided as before is not callable nor a string)")
            return

    # check that after is valid, if it exists
    after = None
    if "after" in pkgConfig:
        after = pkgConfig["after"]
        if not callable(after) and not utils.isString(after):
            utils.eprint("ERROR: Invalid package config received (value provided as after is not callable nor a string)")
            return

    # check for copr definition and enable if found
    if "copr" in pkgConfig:
        copr = pkgConfig["copr"]

        # ensure valid copr (is a string)
        if not utils.isString(copr):
            utils.eprint("ERROR: Invalid package config received (provided copr host is not a string)")
            return

        # run command to enable copr host if not already enabled
        if not coprIsEnabled(copr):
            coprCmd = f"sudo dnf copr enable {copr}"
            print(coprCmd)
            subprocess.run(coprCmd, shell=True)

    if before:
        if callable(before):
            before()
        else:
            subprocess.run(before, shell=True)

    # install packages
    installPackages(pkgList)

    # run after command
    if after:
        if callable(after):
            after()
        else:
            subprocess.run(after, shell=True)

# install a list of flatpaks, passed as a list of strings
def installFlatpaks(pakList, remote="flathub"):
    installPackagesOrPaks(f"flatpak install {remote}", pakList)

# install a special package
def installSpecialFlatpaks(pakConfig):
    # ensure that we have a valid package list
    pakList = []
    if "flatpaks" in pakConfig:
        pakList = pakConfig["flatpaks"]
    elif "flatpak" in pakConfig:
        pakList = pakConfig["flatpak"]
    pakList = cleanPackageInput(pakList)
    if not pakList:
        utils.eprint("ERROR: Invalid flatpak config received (no valid flatpak list found)")
        return

    # check that after is valid, if it exists
    after = None
    if "after" in pakConfig:
        after = pakConfig["after"]
        if not callable(after) and not utils.isString(after):
            utils.eprint("ERROR: Invalid flatpak config received (value provided as after is not callable nor a string)")
            return

    # check for remote definition
    remote = "flathub"
    if "remote" in pakConfig:
        remote = pakConfig["remote"]

        # ensure valid copr (is a string)
        if not utils.isString(remote):
            utils.eprint("ERROR: Invalid flatpak config received (provided flatpak remote is not a string)")
            return

    # install packages
    installFlatpaks(pakList, remote=remote)

    # run after command
    if after:
        if callable(after):
            after()
        else:
            subprocess.run(after, shell=True)

def enableFlatpakRemotes(remotes):
    for remote in remotes:
        if not "name" in remote:
            utils.eprint("ERROR: Invalid flatpak remote received (provided remote has no name)")

        if not "url" in remote:
            utils.eprint("ERROR: Invalid flatpak remote received (provided remote has no url)")

        cmd = f"flatpak remote-add --if-not-exists {remote["name"]} {remote["url"]}"
        print(cmd)
        subprocess.run(cmd, shell=True)

# sets up rpm fusion nonfree
def setupRpmFusion():
    rpmPkgs = [
        "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm",
        "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm",
    ]
    print("Setting up RPM Fusion...")
    installPackages(rpmPkgs)
    print("RPM Fusion Installed...")

# runs the setup steps for downloading a module's packages
def setupModulePackages(module):
    if not hasattr(module, "pkgs"):
        return

    # the list of "normal" packages
    basePkgs = list(filter(utils.isString, module.pkgs))

    # ensure git is installed, needed so config can be saved easily
    basePkgs.append("git")

    # install normal packages
    installPackages(basePkgs)

    # the list of "special" packages with extra instructions
    specialPkgs = list(filter(utils.isDict,module.pkgs))

    # install special packages
    for pkgConfig in specialPkgs:
        installSpecialPackage(pkgConfig)

# runs the package setup steps for all provided modules
def setupPackages(module_list):
    print("Installing packages...")

    for module in module_list:
        setupModulePackages(module)

    print("Package installation complete.")

# enables the flatpak remotes for the provided module
def setupModuleFlatpakRemotes(module):
    if not hasattr(module, "flatpakRemotes"):
        return

    enableFlatpakRemotes(module.flatpakRemotes)

# installs the flatpaks for the given modules
def setupModuleFlatpaks(module):
    if not hasattr(module, "flatpaks"):
        return

    # the list of "normal" flatpaks
    basePaks = list(filter(utils.isString, module.flatpaks))

    # install "normal" flatpaks
    installFlatpaks(basePaks)

    # the list of "special" flatpaks with extra instructions
    specialPaks = list(filter(utils.isDict, module.flatpaks))

    # install special packages
    for pakConfig in specialPaks:
        installSpecialFlatpaks(pakConfig)

# runs the steps for installing flatpaks
def setupFlatpaks(module_list):
    # ensure flatpak is installed
    print("Installing flatpak...")
    installPackages("flatpak")
    print("Flatpak Installed...")

    print("Enabling Flatpak remotes...")
    # ensure flathub is installed
    enableFlatpakRemotes([
        {
            "name": "flathub",
            "url": "https://flathub.org/repo/flathub.flatpakrepo",
        }
    ])
    for module in module_list:
        setupModuleFlatpakRemotes(module)
    print("Flatpak remotes enabled")

    print("Installing flatpaks...")
    for module in module_list:
        setupModuleFlatpaks(module)
    print("Flatpaks installed.")

# the callback function used to run file after-copy functions
def fileAfterRunner(dstPath, written, afterFilesPath, actualPath):
    # the path of the associated after module will be
    homeRelativePath = Path(dstPath).relative_to(actualPath)
    configAfterPath = Path(afterFilesPath) / homeRelativePath
    modulePath = Path(str(configAfterPath) + ".py")

    if modulePath.is_file():
        # import the module
        spec = importlib.util.spec_from_file_location("after", modulePath)
        afterModule = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(afterModule)

        if afterModule.always() or written:
            afterModule.callback(Path(dstPath))

# runs the setup steps for updating system files for a module
def setupModuleSystemDirectories(module):
    module_subdirs = utils.getModuleSubdirectories(Path(module.__file__).parent)

    def fileAfterFunc(dstPath, written):
        fileAfterRunner(dstPath, written, module_subdirs["afterSystemFiles"], Path("/"))

    utils.cpImproved(
        module_subdirs["staticSystemFiles"],
        Path("/"),
        sudo=True,
        after=fileAfterFunc
    )
    utils.cpImproved(
        module_subdirs["templateSystemFiles"],
        Path("/"),
        allowOverwrite=False,
        sudo=True,
        after=fileAfterFunc
    )

# runs the setup steps for updating system files
def setupSystemDirectories(module_list):
    print("Setting up system files...")

    for module in module_list:
        setupModuleSystemDirectories(module)

    print("System file setup complete")

# runs the setup steps for updating the home directory for a module
def setupModuleHomeDirectories(module):
    module_subdirs = utils.getModuleSubdirectories(Path(module.__file__).parent)

    def fileAfterFunc(dstPath, written):
        fileAfterRunner(dstPath, written, module_subdirs["afterUserFiles"], Path("/"))

    utils.cpImproved(
        module_subdirs["staticUserFiles"],
        Path.home(),
        after=fileAfterFunc
    )
    utils.cpImproved(
        module_subdirs["templateUserFiles"],
        Path.home(),
        allowOverwrite=False,
        after=fileAfterFunc
    )

# runs the setup steps for updating the home directory
def setupHomeDirectories(module_list):
    print("Setting up home files...")

    for module in module_list:
        setupModuleHomeDirectories(module)

    print("Home file setup complete")

# installs a single font to the machine, given as a path
def installFontByPath(path):
    fontDir = Path.home() / ".local/share/fonts"

    extension = "".join(path.suffixes)
    name = path.stem
    outputPath = os.path.join(str(fontDir), name)

    def installZip(path):
        subprocess.run(f"unzip {str(path)} -d {outputPath}", shell=True)

    installRouter = {
        ".zip": installZip
    }

    if extension in installRouter:
        installRouter[extension](path)
    else:
        utils.eprint(f"ERROR: Unable to handle font with extension '{extension}'")

# runs the setup steps for downloading and installing fonts
def installModuleFonts(module):
    if not hasattr(module, "fontUrls"):
        return

    fontDir = str(Path.home() / ".local/share/fonts")
    subprocess.run(f"mkdir -p {fontDir}", shell=True)

    for url in module.fontUrls:
        if not utils.isString(url):
            utils.eprint("ERROR: Got invalid font data (nonString url)")
            break;
        
        with tempfile.TemporaryDirectory() as tempDir:
            subprocess.run(f"curl --output-dir {tempDir} -LO {url}", shell=True)

            files = list(Path(tempDir).glob('*'))

            if files:
                fontFile = files[0]
                installFontByPath(fontFile)
            else:
                utils.eprint(f"ERROR: Unable to zipfile download from {url}")
                break;
            
# sets up all fonts
def setupFonts(module_list):
    print("Setting up fonts...")

    for module in module_list:
        installModuleFonts(module)

    subprocess.run("fc-cache -f -v", shell=True)

    print("Font setup complete")

# runs the after function in options.after()
def runModulePostSetup(module):
    afterFunc = getattr(options, "after", None)
    if callable(afterFunc):
        afterFunc()

# runs all post setup steps in every module
def runPostSetup(module_list):
    print("Running options.after()...")

    for module in module_list:
        runModulePostSetup(module)

    print("options.after() complete")


# runs all setup steps
def setupAll(module_list):
    setupRpmFusion()
    setupPackages(module_list)
    setupFlatpaks(module_list)
    setupFonts(module_list)
    setupSystemDirectories(module_list)
    setupHomeDirectories(module_list)
    runPostSetup(module_list)

def main():
    module_list = importEnabledModules(MODULE_CONFIG_PATH)

    prompt = ("Press a key to select a setup option:\n"
        "a - set up all (excluding disabled modules)\n"
        "h - set up home directories only\n"
        "s - set up system directories only\n"
        "f - set up fonts only\n"
        "k - set up flatpaks only\n"
        "p - set up packages only\n"
        "r - set up rpm fusion\n"
        "z - run post setup only\n"
        "q - quit\n")

    cancelWarning = "Setup Cancelled."

    actionMap = {
        "a": lambda: setupAll(module_list),
        "s": lambda: setupSystemDirectories(module_list),
        "h": lambda: setupHomeDirectories(module_list),
        "f": lambda: setupFonts(module_list),
        "k": lambda: setupFlatpaks(module_list),
        "p": lambda: setupPackages(module_list),
        "r": setupRpmFusion,
        "z": lambda: runPostSetup(module_list),
    }

    try:
        char = None
        while char != "q":
            char = input(prompt)

            if char in actionMap:
                actionMap[char]()
                print("Quick Setup Complete!")
                return
        if char == "q":
            print(cancelWarning)
    except KeyboardInterrupt:
        print(cancelWarning)

if __name__ == "__main__":
    main()
